sudo: false

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g gatsby-cli

jobs:
  include:
    - stage: Build
      install: yarn install --frozen-lockfile
      script: gatsby build